### ISSUE TITLE
атрибут action

### ISSUE THREAD

**Issue by vladimirGlinskikh** [badziy/ru.badziy.spring.mvc#1]
Атрибут action 
Этот атрибут определяет, куда отправляются данные. Его значение должно быть действительным URL.

В данном случае showDetails не подпадает под понятие URL, так, как не является ни абсолютным, ни относительным. Так писать `<form action="showDetails" method="get">,` плохая практика.

**Comment by vladimirGlinskikh** [comment]
> Атрибут action Этот атрибут определяет, куда отправляются данные. Его значение должно быть действительным URL. Есть два вида урла. Абсолютный и относительный. В данном случае showDetails не подпадает под понятие URL, так, как не является ни абсолютным, ни относительным. Так писать `<form action="showDetails" method="get">,` плохая практика. В дальнейшем, при таком подходе, можешь получить много танцев с бубном.

**Comment by badziy** [comment]
Приму к сведению. Спасибо.
